### ISSUE TITLE
Detailed documentation to explain compatibility of MuSig2 with Schnorr 340

### ISSUE THREAD

**Issue by curiecrypt** [input-output-hk/musig2#15]
We have made some [tweaks](https://github.com/input-output-hk/musig2#verify-musig2-with-secp256k1_schnorrsig_verify:~:text=Verify-,MuSig2,-with%20secp256k1_schnorrsig_verify) to make MuSig2 verifiable by `secp256k1_schnorrsig_verify`. We must ensure this won't cause any security flaws and document the changes.

**ToDo:**

- [ ] Describe the security arguments of BIP340.
- [ ] Analyze the security assumptions of MuSig2 (OMDL) wrt BIP340.
- [ ] Explain the differences in the implementation with the paper.
